### ISSUE TITLE
Add a message with the items / coins you received / traded

### ISSUE THREAD

**Issue by KhrysAK47** [erikzimmermann/TradeSystem#257]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem at all. But it would look cool if after a trade has been completed each player gets a message that lists them all the items / coins traded like Hypixel (screenshot below).

**Describe the solution you'd like**
Not Applicable

**Describe alternatives you've considered**
Not Applicable

**Additional context**
If you get a item from trading it's displayed as &a+, if you gave one, as &c-
https://imgur.com/a/yzp4DGF

**Discord contact**: <name>#<id>
Quality Setups#4443

**Comment by iVillager** [comment]
It would be better if at least the coins are displayed. Items will spam a lot :/

**Comment by UnitedCraft** [comment]
if there was a message in the chat how much someone got after completing the trade with (essentials, xp points and token manager) it would be so great and amazing!

**Comment by erikzimmermann** [comment]
![image](https://user-images.githubusercontent.com/23747243/225584845-0c79ff59-09bd-4ac1-bc30-cde50f4a5ad7.png)
* Can be configured in the language file like:
```
Trade_Finish_Report_Receive: "  &a+ &7%object%"
Trade_Finish_Report_Give: "  &c- &7%object%"
Trade_Finish_Report_Object_Item: "%amount%x %item%"
```

There's an additional event to change item and economy names.
