### ISSUE TITLE
EXPERIENCE DUPE

### ISSUE THREAD

**Issue by fra130701** [erikzimmermann/TradeSystem#290]
I found a duplication bug with exp trading
When you trade exp, levels are stacked other levels,
if players1 trades 20 levels to player2, and player2 already has 10 levels, his balance becomes of 30 levels, in this way you can dupe levels because 20 levels from 0 are different from 20 levels from 10

Example:
Player1 has 10 levels, player2 has 10 levels, if player1 trades with player2 10 levels, player2 experience is stacked to 20.
But the 10 levels of player1 wanst from 10 to 20 but from 0 to 10.

You must use experience orbs and not levels..

Sorry for bad english

**Comment by CodingAir** [comment]
Unfortunately, I cannot solve this since it just allows to trade levels. Switching to exp points solves this.

**Comment by fra130701** [comment]
I can't remove because /ts layout is broken on the latest update too..

**Comment by fra130701** [comment]
i sent you a video on discord

**Comment by luizsusin** [comment]
> Unfortunately, I cannot solve this since it just allows to trade levels. Switching to exp points solves this.

Actually, you can. Calculate the amount of exp in the amount of levels to exp points by using:
`(level)^2 + 6*(Level)` (at levels 0-16)
`2.5*(level)^2 - 40.5*(level) + 360` (at levels 17-31)
`4.5*(level)^2 - 162.5*(level) + 2220` (at level 32+)

Then, get the amount of exp the target player currently has and sum this up. Remove the amount of exp from the source player. This will prevent the dupe and would make trades a lot easier by selecting the amount of levels to its equivalent amount of exp.

(Source: [Official Minecraft Wiki](https://minecraft.fandom.com/wiki/Experience#Leveling_up))

**Comment by CodingAir** [comment]
> > Unfortunately, I cannot solve this since it just allows to trade levels. Switching to exp points solves this.
> 
> Actually, you can. Calculate the amount of exp in the amount of levels to exp points by using:
> `(level)^2 + 6*(Level)` (at levels 0-16)
> `2.5*(level)^2 - 40.5*(level) + 360` (at levels 17-31)
> `4.5*(level)^2 - 162.5*(level) + 2220` (at level 32+)
> 
> Then, get the amount of exp the target player currently has and sum this up. Remove the amount of exp from the source player. This will prevent the dupe and would make trades a lot easier by selecting the amount of levels to its equivalent amount of exp.
> 
> (Source: [Official Minecraft Wiki](https://minecraft.fandom.com/wiki/Experience#Leveling_up))

Unfortunately, I know a few people who customize this. So I cannot really use this equation...

**Comment by TizoCraft** [comment]
would be great if this could get fixed.
