### ISSUE TITLE
Shulker Peeking in Trade Menu.

### ISSUE THREAD

**Issue by UsainSrht** [erikzimmermann/TradeSystem#297]
Trade system will be perfect if we can see what inside of shulker box that putted in trade menu.

Shulker boxes can be used to trick players because players can only see few first items in shulker box and that item's names can be changed. So my solution is when you right click a shulker box in trade menu a new menu will open and you can see what inside of shulker box.

![Screenshot_1](https://user-images.githubusercontent.com/59025999/121773466-d7b4bd00-cb84-11eb-9e16-07a49ea16613.png)

nether star is a back to trade button
black stained glass panes are just decorative

UsainSrht#4957

**Comment by UnitedCraft** [comment]
It would be nice to have that option!
