### ISSUE TITLE
GrandEconomy/EnderPay support

### ISSUE THREAD

**Issue by bonobo-craft** [erikzimmermann/TradeSystem#318]
**Description**
Currently TradeSystem only supports Vault and Essentials. But there are other popular economy mods which currently are not supported like:

* EnderPay (with a nice ingame UI on balance)
* GrandEconomy (which is a swiss army knife of economy systems that can use Enderpay, Vault, Essentials and many other economy mods as a backend). It provides a unified API for economy consuming plugins/mods.

**Solution**
I think that adding GrandEconomy will give your trading system ability to be economy-backend independent. Also it could remove the necessity of supporting Vault and Essentials directly.

**Alternative**
Maybe just adding EnderPay support is easier than consuming a GrandEconomy API.

**Additional context**
https://www.curseforge.com/minecraft/mc-mods/grand-exchange
https://www.curseforge.com/minecraft/mc-mods/enderpay

**Discord contact**: <name>#<id>
pureluck#7595

**Comment by CodingAir** [comment]
Does EnderPay still work on 1.17.1?

**Comment by pure-luck-999** [comment]
Enderpay is 1.12.2 I believe

**Comment by erikzimmermann** [comment]
Outdated
