### ISSUE TITLE
can change the number of decimal place of money in the trade

### ISSUE THREAD

**Issue by siulung201314** [erikzimmermann/TradeSystem#326]
**Is your feature request related to a problem? Please describe.**
The max number of decimal place of money is forced to be 4 but some users may not want 4 decimal places.

**Describe the solution you'd like**
Users can change the max number of decimal place of money in the trade by themselves.

**Comment by CodingAir** [comment]
I added this limit to avoid calculation errors in Java. I can also move this limit to 6 or 8 decimals but I won't completely remove this.

**Comment by erikzimmermann** [comment]
Done with #395
