### ISSUE TITLE
Support PlayerPoints

### ISSUE THREAD

**Issue by j4pa0** [erikzimmermann/TradeSystem#342]
**Is your feature request related to a problem? Please describe.**
My server mainly use PlayerPoints, so lacking the support of PlayerPoints for the TradeSystem is a big shortcoming.

**Describe the solution you'd like**
I'd like you to support PlayerPoints in TradeSystem.

**Discord contact**: japaodsc#5786

Thanks in advance.

**Comment by CodingAir** [comment]
PlayerPoints and TradeSystem both support Vault. Did you try it with that?

**Comment by saffue** [comment]
any chance on this getting support?

**Comment by erikzimmermann** [comment]
> any chance on this getting support?
> 
> 

Could you please provide me with a link to the resource or API? I'll consider it for the next release

**Comment by saffue** [comment]
i can do better heres both lol
spigot listing - https://www.spigotmc.org/resources/playerpoints.80745/
API -https://github.com/Rosewood-Development/PlayerPoints/wiki/API-Getting-Started
