### ISSUE TITLE
Vault sign not opening with Lunar Client 1.8.9

### ISSUE THREAD

**Issue by Redwolf223** [erikzimmermann/TradeSystem#361]
**Describe the bug**
When you try to set the amount of money you want to trade the sign will not appear when using the Lunar Client 1.8.9

**To Reproduce**
Use Lunar Client
Send a trade request
Click on the Vault item

**Expected behavior**
To the sign to appear when using the Lunar Client 1.8.9

**Screenshots**
![image](https://user-images.githubusercontent.com/58572866/151719428-08b70a32-c218-4ef9-bc64-16f67dc0eac8.png)

**Comment by Kaesor** [comment]
I've the similar bug, with a Bedrock player, when i use SIGN (i can't use ANVIL, because there is a level requirement), the sign don't appear.

**Comment by ItzKiwiSap** [comment]
I'm experiencing this issue on my server as well. For both Bedrock/PE player (Geyser) and Java players (No idea if this is related to Lunar)

**Comment by erikzimmermann** [comment]
@ItzKiwiSap Which MC version are you using?

**Comment by ItzKiwiSap** [comment]
1.19.4
