### ISSUE TITLE
/trade toggle

### ISSUE THREAD

**Issue by xPoyraz** [erikzimmermann/TradeSystem#363]
I am using trade proxy plugin and there is a trade plugin on multiple servers, when a player uses the /trade toggle command on one server, trade requests are not received, but when he switches to another server he has to use this command again. Can you pass this data to all servers with the trade proxy plugin?

**Discord contact**: Poyraz#3391

**Comment by Arkhe002** [comment]
+1

**Comment by umutc2n** [comment]
upp
