### ISSUE TITLE
Optimizing onPickup event

### ISSUE THREAD

**Issue by ItsSynchro** [erikzimmermann/TradeSystem#366]
**Describe the bug**
I ran a spark report and had TradeSystem using 21.96% of the Server Thread due to the onPickup event.
https://spark.lucko.me/ld9L7nw9kq

**To Reproduce**
None

**Expected behavior**

**Screenshots**

**Additional context**
Server version 1.18.1
Plugin Version 2.0.10

**Discord contact**: Synchro#7160

**Comment by ItsSynchro** [comment]
Updated Spark as of 3/26/2022
https://spark.lucko.me/Y5ZszZLk9F

**Comment by ItsSynchro** [comment]
Updated Spark as of 4/3/2022
https://spark.lucko.me/gxFmnigwJG

**Comment by ItsSynchro** [comment]
Updated Spark as of 6/5/2022
https://spark.lucko.me/gY5q8vz3CE

**Comment by ItsSynchro** [comment]
Updated Spark as of 6/27/2022
https://spark.lucko.me/rQSCVCRO9s

**Comment by erikzimmermann** [comment]
Fixed
