### ISSUE TITLE
Tradelog Database Password Error

### ISSUE THREAD

**Issue by RhinoCD** [erikzimmermann/TradeSystem#369]
**Describe the bug**
My database password for my host has a ! in the password, due to this it is throwing an error in the config and is not letting me use the ! as part of the password

**To Reproduce**
go to config.yml and for db_password type a ! mark

**Expected behavior**
The tradelog will not work and the sounds part under the tradelog will get deleted

**Screenshots**

**Additional context**

**Discord contact**: <name>#<id>

**Comment by CodingAir** [comment]
Works fine for me. Did you try to add quotation marks?
