### ISSUE TITLE
Change the name of the Anvil coin input GUI

### ISSUE THREAD

**Issue by AydaaCraft** [erikzimmermann/TradeSystem#381]
**Is your feature request related to a problem? Please describe.**
I like to customise the GUI's on my server and being able to rename the anvil GUI helps with custom GUIs

**Describe the solution you'd like**
Ability to rename the anvil GUI screen name

**Describe alternatives you've considered**

**Additional context**
Ill get an image shortly

**Discord contact**: Adelando#1988

**Comment by AydaaCraft** [comment]
<img>https://cdn.discordapp.com/attachments/615011617780006915/967048513013809222/IMG_7076.png</img>

**Comment by ColorsASD** [comment]
+ paper name and lore change in config.

Currently, I can only rewrite the title of the anvil by reverse engineering. :(

![image](https://user-images.githubusercontent.com/12263156/209717129-a7bd152a-801d-4622-aa3d-eb8fc7f43e0f.png)
![image](https://user-images.githubusercontent.com/12263156/209717158-771b729f-42ad-4860-9e77-6270e5cc1e79.png)
