### ISSUE TITLE
disable commas

### ISSUE THREAD

**Issue by Kocimietka7192** [erikzimmermann/TradeSystem#393]
Please add the option to disable commas - scammers often do this, people think that they exchange for 40,000 and they exchange for 400.00

**Comment by dorsax** [comment]
I suggest to add proper localization instead of prohibiting decimal values to not break economic systems depending on this. Localization can then either be configured via config, lang or even client side (which isn't good practice).

**Comment by erikzimmermann** [comment]
Done with #395
