### ISSUE TITLE
String is null

### ISSUE THREAD

**Issue by Zoiter7** [erikzimmermann/TradeSystem#396]
I don't know how to reproduce the error, randomly appeared, I saw the console and get spam with this error, and finally all players have been kicked due error.

The error is in **de.codingair.tradesystem.lib.codingapi.player.data.PacketReader** class.

https://www.toptal.com/developers/hastebin/bobesigotu.php

Using latest paper and used plugin v2.1.2 (Updated today to 2.1.3)

**Comment by erikzimmermann** [comment]
This in particular is not a bug related to TradeSystem. The packet reader which is logged there just forwards packets or block them entirely. So it must be another plugin since TradeSystem does not modify any packets.
