### ISSUE TITLE
Dynamic Entries/Heads/Skulls in GUI 

### ISSUE THREAD

**Issue by Osamu01** [erikzimmermann/TradeSystem#399]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
It's unclear what the status button is, so it would be cool if we could set them as dynamic textures as opposed to only static textures, in this specific case for player heads/skulls. 

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
Either implement a usable placeholder to be used in the config for dynamic player skulls where needed or add it to the example configs/layouts so it's easier to understand how to do so yourself.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
I tried looking up PAPI placeholders and such, but I'm not very tech savvy and couldn't come up with anything.

**Additional context**
_Add any other context or screenshots about the feature request here._
N/A

**Discord contact**: Fenton#2474

**Comment by Rectos28** [comment]
It will be helpful if placeholder for player head for each the trader and trader partner so we can show them in the GUI. Also spesific  placeholder for each one like ` trader-%player_name% ` and ` pratner-%player_name% ` and this concept can be used for other placeholder like the economy and etc.

**Comment by erikzimmermann** [comment]
The status icons now support displaying the player heads. You only have to insert the default player head item in there. Another icon will come where you can have an additional "decoration" icon that displays player heads without any additional functionality.

**Comment by Willydaham09** [comment]
Where did hotfix 4 go? All I see is hotfix 3

**Comment by erikzimmermann** [comment]
Yeah sorry. There was an issue with that version.
