### ISSUE TITLE
New Placeholder

### ISSUE THREAD

**Issue by samparotony228** [erikzimmermann/TradeSystem#402]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a placeholder that counts how many successful trades a player has made.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Discord contact**: Samparo#0001

**Comment by erikzimmermann** [comment]
This would require some sort of database and I don't really know if this is something that should be introduced only for counting trades...

**Comment by samparotony228** [comment]
❤️
