### ISSUE TITLE
Task #6321327 for TradeSystem v2.1.3 generated an exception

### ISSUE THREAD

**Issue by puritynetwork** [erikzimmermann/TradeSystem#416]
This error comes up in the console. Could you please tell me how to solve it

![Immagine 2022-12-30 142439](https://user-images.githubusercontent.com/120317607/210074916-090c0629-5ad9-49c8-bc60-279bc3f0b66e.png)

**Comment by ArmonicPvP** [comment]
This happens for me as well. Players can no longer trade money since this started. 1.19.3

**Comment by korallo159** [comment]
Same

**Comment by erikzimmermann** [comment]
Please try the hotfix from my Discord server. You can find it in the devbuilds channel for tradesystem.

**Comment by korallo159** [comment]
@erikzimmermann please see https://github.com/erikzimmermann/TradeSystem/pull/417
