### ISSUE TITLE
Prefix move to language.yml

### ISSUE THREAD

**Issue by Deichor** [erikzimmermann/TradeSystem#429]
**Is your feature request related to a problem? Please describe.**

Move prefix for placeholder and more color support.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Discord contact**: <name>#<id>

**Comment by erikzimmermann** [comment]
Note: The prefix was not moved to the language files but now just supports papi placeholders and \n breaks. Colors were already supported with either `&a` or `&#123456`
