### ISSUE TITLE
[DUPE] 

### ISSUE THREAD

**Issue by Saidas25** [erikzimmermann/TradeSystem#434]
**Describe the bug**
a dupe bug, in layout editor
**To Reproduce**
1. Go to '/tradesystem layout edit Standard'
2. Click on 'status preview/icon'
3. Take the block for button out
4. cancel
5. go back into there, and the block you took out is still there
6. you can take the block out of there infinite amount of times, duping it
**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Discord contact**: <name>#<id>
25#2138

**Comment by erikzimmermann** [comment]
This is only applied to the layout editor which is intended. It's only a dupe glitch if users can duplicate their items. In this case, your players should not have access to the layout editor.

Gonna close this issue for now... You can comment any time.
