### ISSUE TITLE
<Title> Tradelog don't show the correct quantity

### ISSUE THREAD

**Issue by Press22300** [erikzimmermann/TradeSystem#444]
When we trade multiple items, for example SHulkersBoxs, the quantity isn't wrote correctly

**Discord contact**: Press#0001
![image](https://github.com/erikzimmermann/TradeSystem/assets/121343872/80973510-973a-41c6-8cce-0945acc2b8dd)

**Comment by erikzimmermann** [comment]
Duplicated #440
