### ISSUE TITLE
Item Display Names On %item% (If Applicable)

### ISSUE THREAD

**Issue by KhrysAK47** [erikzimmermann/TradeSystem#448]
**Is your feature request related to a problem? Please describe.**
Take the color codes and formatting of the item names you trade that will overwrite the name in %item% as right now it displays as <vanilla item name> <custom name>, so either a setting to display only the custom name if applicable or similar.

**Describe the solution you'd like**
Take the color codes and formatting of the item names you trade that will overwrite the name in %item% as right now it displays as <vanilla item name> <custom name>, so either a setting to display only the custom name if applicable or similar.

**Describe alternatives you've considered**
Not Applicable

**Additional context**
Not Applicable

**Discord contact**: Khrys#2160

**Comment by erikzimmermann** [comment]
It already displays e.g. "+1 Iron Sword (DISPLAY NAME)".

**Comment by KhrysAK47** [comment]
The suggestion consists in adding an option to disable the first part of it, only allowing it to display the display name of the item (if applicable), or the item id name if not applicable.

**Comment by KhrysAK47** [comment]
@erikzimmermann
