### ISSUE TITLE
Setting a message to '' makes it not show up.

### ISSUE THREAD

**Issue by 0bviouslee** [erikzimmermann/TradeSystem#449]
**Is your feature request related to a problem? Please describe.**
In my server, we have another plugin that sends notifications for trades and having an option to disable TradeSystems messages would make them look better.

**Describe the solution you'd like**
Setting any message to '' in the messages file makes it not appear in game.

**Discord contact**: Obviouslee#2925

**Comment by erikzimmermann** [comment]
This issue requires refactoring of all sendMessage occurances.

**Comment by xuandattnvn1995** [comment]
up. 
I made the system to enable/disable trade using the gui
so i want to remove the notification message because it already shows enable/disable on gui
![image](https://github.com/erikzimmermann/TradeSystem/assets/25878455/fe8b484c-ad81-456f-b2aa-69a8391b2f19)
