### ISSUE TITLE
Add Korean Language

### ISSUE THREAD

**Issue by BackSam6348** [erikzimmermann/TradeSystem#451]
**Is your feature request related to a problem? Please describe.**
Need add korean lang support

**Describe the solution you'd like**
korean support or crowdin korean project start

**Describe alternatives you've considered**
start crowdin korean project or examplelang.yml use try

**Additional context**
Nope

**Discord contact**: <name>#<id>

**Comment by erikzimmermann** [comment]
You can simply copy the `ENG.yml` file to start your own translation.
