### ISSUE TITLE
<Could not pass event PlayerJoinEvent to TradeSystem v2.3.1>

### ISSUE THREAD

**Issue by AdamDAuria** [erikzimmermann/TradeSystem#453]
**Could not pass event PlayerJoinEvent to TradeSystem v2.3.1**
Spamming in the Console

**To Reproduce**
1. Purpur 1.20.1 Version
2. Start the server
3. See error

**Expected behavior**
No Console Spam

**Screenshots**
File be attached

**Additional context**
Nothinng
**Discord contact**: <AdamDAuria>#<25581>
[Could_not_pass_event_PlayerJoinEvent_to_TradeSystem_v2.3.1.txt](https://github.com/erikzimmermann/TradeSystem/files/11765150/Could_not_pass_event_PlayerJoinEvent_to_TradeSystem_v2.3.1.txt)

**Comment by erikzimmermann** [comment]
Please use the latest version from my Discord server.
