### ISSUE TITLE
Automatic Layout change to default

### ISSUE THREAD

**Issue by UnitedCraft** [erikzimmermann/TradeSystem#460]
**Describe the bug**
Sometimes after restarting the server, it changes the trade layout to the default one - I don't know why. In addition, when you restore your layout, one of the functions is removed, e.g. once tokenmanager, once vault

**Expected behavior**
The activated layout never changed

**Additional context**
Latest version

**Comment by erikzimmermann** [comment]
This happens most probably due to a missing plugin causing the reset to the default layout.
