### ISSUE TITLE
Item Names, mmoitem in Trade Log

### ISSUE THREAD

**Issue by xuandattnvn1995** [erikzimmermann/TradeSystem#463]
in #433 
nothing seems to have changed
![image](https://github.com/erikzimmermann/TradeSystem/assets/25878455/878701e3-246e-424c-ac50-7d0cbc2012dd)
![image](https://github.com/erikzimmermann/TradeSystem/assets/25878455/20e49e58-1182-4534-b0eb-db077505ef2d)
name item:
![image](https://github.com/erikzimmermann/TradeSystem/assets/25878455/8bab9eed-86f6-4d2a-8093-a40a3dbac39c)
![image](https://github.com/erikzimmermann/TradeSystem/assets/25878455/07024557-2d3d-4ad1-b7b1-fcb75b1b1641)

**Comment by erikzimmermann** [comment]
Hi, what exactly do you want to see in your logs?

**Comment by xuandattnvn1995** [comment]
if is mmoitem: LXD_VN đã nhận 1xMMOITEM.ARMOR_VANILLA.NETTHERITE_LEGGINGS
it will give me information which item in plugin: MMOITEMS, file: ARMOR_VANILLA, item: NETHERITE_LEGGINGS
This makes it possible for me to look up item information

**Comment by erikzimmermann** [comment]
Please contact me on Discord for testing.
