### ISSUE TITLE
Players lose their items in the trade GUI

### ISSUE THREAD

**Issue by siulung201314** [erikzimmermann/TradeSystem#465]
**Describe the bug**
Players lose their items in the trade GUI

**To Reproduce**
1. Players A's inventory is full.
2. Player B trades with player A and they put some items in the trade GUI.
3. When player A throws away some items from his inventory, some of the items in the trade GUI disappear.

**Expected behavior**
The items should not disappear in the trade GUI

TradeSystem verison 2.3.2
Purpur-2011 (MC 1.20.1)

**Comment by erikzimmermann** [comment]
Unfortunately, I cannot reproduce this issue with latest paper as well as purpur-2011 and TradeSystem 2.3.2. Maybe, this is something relate to some other plugins you use?

**Comment by siulung201314** [comment]
I am not sure what plugin may be related.
I think the possbile related plugin is commandpanel because it is a plugin that can create gui.
https://www.spigotmc.org/resources/commandpanels.67788/
