### ISSUE TITLE
ClassCastException Packet encoding of packet ID 82 threw (skippable? false)

### ISSUE THREAD

**Issue by Nishh** [erikzimmermann/TradeSystem#472]
**Describe the bug**
Players are kicked with random errors, also an exception in console.
https://pastebin.com/t3qEKjtD

**To Reproduce**
I think it happens when some packets are sent to players, not sure which ones.

**Additional context**
Server version: Paper 1.19.4
TradeSystem version: 2.3.3 (current latest)
ProtocolLib version: 5.0.0 (current latest)

**Discord contact**: nish951

**Comment by erikzimmermann** [comment]
This issue occurs when sending a packet. Don't know which one. But you can see that the packet is sent with the API of ProtocolLib which I don't use. 

> at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:443) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
