### ISSUE TITLE
hex colors support

### ISSUE THREAD

**Issue by samparotony228** [erikzimmermann/TradeSystem#485]
**Is your feature request related to a problem? Please describe.**
support for hex colors.

**Describe the solution you'd like**
be able to use hex colors in plugin localization files.

**Describe alternatives you've considered**
-

**Additional context**
hex color use case can be any at the discretion of you as a developer. e.g. "&#hex", "#hex", "<#hex>", "{#hex}".

**Discord contact**: samparo

**Comment by erikzimmermann** [comment]
Hex-colors are already supported in the language file e.g. &#123456. Where exactly is it not supported?

**Comment by samparotony228** [comment]
> 

Honestly, I have not tried this use case, the fact is that I did not find information about it on the spigot page of the plugin. I'll double check now and let you know.

**Comment by samparotony228** [comment]
Sorry for the late reply, I completely forgot about this. The hex color format you mentioned works. Thanks for the help!
