### ISSUE TITLE
User can drop items

### ISSUE THREAD

**Issue by Perwollnt** [erikzimmermann/TradeSystem#490]
**Describe the bug**
When in the trade menu a user can drop items by dragging them outside the gui and releasing them

**To Reproduce**
1. trade someone
2. drag item out of gui
3. press left click

**Expected behavior**
The drop event is cancelled and the item goes back to player inventory

**Screenshots**
no screenshot

**Additional context**
the DM video

**Discord contact**: perwollnt

**Comment by KhrysAK47** [comment]
Bump
