### ISSUE TITLE
Drop Bug

### ISSUE THREAD

**Issue by KhrysAK47** [erikzimmermann/TradeSystem#491]
**Describe the bug**
When a player drop event is cancelled (whether by plugin, worldguard flag, etc), they can still drop items in a Trading menu. 

**To Reproduce**
1. Define a region where players can't drop items. /rg flag <region> item-drop deny
2. Engage in trading with someone.
3. Drop items while in menu.

**Expected behavior**
Event should be cancelled.

**Screenshots**
N/A

**Additional context**
N/A

**Discord contact**: khrystyian

**Comment by Perwollnt** [comment]
As an extension to this one: My issue is the same, I have sent the video on discord.
https://github.com/erikzimmermann/TradeSystem/issues/490
