### ISSUE TITLE
Adding Multipaper support

### ISSUE THREAD

**Issue by DaJMaN4** [erikzimmermann/TradeSystem#497]
**Is your feature request related to a problem? Please describe.**
The plugin dosent recognize that a multipaper instance is a separate server to another multipaper instance

**Describe the solution you'd like**
Check if the server is running multipaper, just by checking the name of engine and then mark it as separate servers

Multipapers repository with some docs: https://github.com/MultiPaper/MultiPaper

**Discord contact**: dajman4

**Comment by erikzimmermann** [comment]
Please consider switching to Folia. Folia support will come soon (#544)
