### ISSUE TITLE
Problem with implementing API into own plugin.

### ISSUE THREAD

**Issue by EncryptSL** [erikzimmermann/TradeSystem#504]
**Describe the bug**
1. I have problem with include api of TradeSystem into my own custom economy plugin.

2. When i try implement EditorInfo, IDE can't find  de.codingair.codingapi.tools.items.ItemBuilder, because is not implemented in api but is shaded in de.codingair.tradesystem.lib.codingapi.tools.items.ItemBuilder.

3. This is primary not my issue, i can manually implement your library into my project.

4. When i try compile plugin  with added for compileOnly("com.github.CodingAir:CodingAPI:1.77"), plugin after load on enabled server dump 
```
23:52:31[ERROR] [CreditLite] Failed to register events for class com.github.encryptsl.credit.hook.tradesystem.TradeSystemListener because de/codingair/codingapi/tools/items/ItemBuilder does not exist.
```
5. Okay, plugin can't find class, Now i know can't only compile library, next i'm tried create shade in my plugin without success TradeSystem dump **error** https://paste.hostify.cz/?e0f6c165e26f45fa#6TZwtjpt94irpSvETFNtwMHNPspWTTDKACvuFLo7f3dw

**Screenshots**
![Snímek obrazovky 2024-01-18 000045](https://github.com/erikzimmermann/TradeSystem/assets/9441083/cd68f51b-1e41-467f-a332-34247b74f3c0)

![Snímek obrazovky 2024-01-18 004314](https://github.com/erikzimmermann/TradeSystem/assets/9441083/128d0212-29ab-4206-854d-3d984c6cce58)

![Snímek obrazovky 2024-01-18 004421](https://github.com/erikzimmermann/TradeSystem/assets/9441083/2f4ab18b-bc2d-43e1-ba62-cb47769a9e5c)

**Comment by erikzimmermann** [comment]
Please take a look at the updated README.md on the main page: https://github.com/erikzimmermann/TradeSystem
