### ISSUE TITLE
<Title>log display incomplete

### ISSUE THREAD

**Issue by zfms4188** [erikzimmermann/TradeSystem#512]
**Describe the bug**
log display incomplete;I have conducted a large number of transactions, but can only retrieve a small portion
**To Reproduce**
3. See error
/tradelog
**Expected behavior**
I can turn the page or do something else
**Screenshots**

**Additional context**

**Discord contact**: <name>#<id>

**Comment by erikzimmermann** [comment]
The log command has been moved to [TradeAudit](https://www.spigotmc.org/resources/trade-audit-view-ongoing-trades.111665/). Please implement your own SQL queries for individual calculations.
