### ISSUE TITLE
[DUPE] clone item trade 

### ISSUE THREAD

**Issue by eskabal** [erikzimmermann/TradeSystem#514]
found a critical bug in the plugin that allows item duplication during player trades. This issue occurs when a player is engaged in a trade and decides to throw out an item while the trade is ongoing.

Under normal circumstances, items discarded during a trade should not be duplicated. However, I've observed that this particular plugin has a vulnerability that enables the duplication of items. When a player attempts to discard an item during an ongoing trade, it unintentionally triggers the duplication, resulting in an incorrect quantity of the respective item in the game's economy.

**Comment by Coloboks** [comment]
Can you send a video?

**Comment by erikzimmermann** [comment]
Outdated, please re-open if this still occurs.
