### ISSUE TITLE
<Title> gui for /trade playername 

### ISSUE THREAD

**Issue by CayanNet** [erikzimmermann/TradeSystem#515]
**Is your feature request related to a problem? Please describe.**
i am wondering can you add the gui for /trade with players skull? so let them click the player head to choose the trade
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Discord contact**: <name>#<id>

**Comment by erikzimmermann** [comment]
Hey, thanks for your ticket. However, I think this might be out of scope and not really useful for all users.
