### ISSUE TITLE
Console Error when adding Currency to Trade

### ISSUE THREAD

**Issue by KhrysAK47** [erikzimmermann/TradeSystem#516]
**Describe the bug**
When players are adding Currency to trades it closes the GUI and shows this error in console: https://pastebin.com/RT9uTgs5

**To Reproduce**
I am unsure, as I only updated it to latest version and it started happening.

**Expected behavior**
It should not close the GUI and the error should not be there.

**Screenshots**
N/A

**Additional context**
N/A

**Discord contact**: khrystyian

**Comment by erikzimmermann** [comment]
Should be fixed by deleting the TradeSystem directory. The layout has been modified manually probably.
