### ISSUE TITLE
Plugin not reloading properly

### ISSUE THREAD

**Issue by Schroddinger** [erikzimmermann/TradeSystem#520]
**Describe the bug**
When reloading the plugin, the autocomplete stops working.
An example: 
Using `/ts layout` will keep autocompleting to `/ts layout layout` instead of `/ts layout <activate/craete/delete/edit>`

Some commands will also break, this was tested using, I'm not very sure if it works for other commands:
Executing `/tradesystem:tradelog` should return a message asking to use **TradeAudit**, after a reload the command no longer exists.
This was tested with **TradeAudit** installed, could also be an incompatibility.

**To Reproduce**
1. Use `/ts reload` (`reload` keyword doesn't autocomplete, has to be written manually)
2. Try autocompleting `/ts layout`
3. Try executing other commands like `/tradelog`
4. If the error didn't trigger, try reloading again (For me, it happens at first or second reload).

**Expected behavior**
The autocomplete should keep working properly.
The commands should still be recognized (even if it just return the message to use the other plugin)

**Screenshots**
![image](https://github.com/erikzimmermann/TradeSystem/assets/11415969/8c67d6a5-9460-4348-a29c-61e494ba07de)

**Additional context**
No additional context

**Discord contact**: duoslingo

**Comment by erikzimmermann** [comment]
Works fine for me with the latest version.

**Comment by erikzimmermann** [comment]
Please comment, if this is still an active issue.

**Comment by Schroddinger** [comment]
Hi, this happened long ago, I no longer use this plugin. Give me a few days and I can try to recreate this error if I manage to find a backup from that time.
