### ISSUE TITLE
Money Trade Input (UPDATED!)

### ISSUE THREAD

**Issue by KhrysAK47** [erikzimmermann/TradeSystem#530]
**Describe the bug**
Occasionally when inputting money to trades, they are cancelled / got back to trading GUI without adding the money to the trade.

**To Reproduce**
I am not entirely sure as it gets reported randomly.

**Expected behavior**
The trade should not be cancelled or returned to the trading GUI without putting the money, it should put the money properly.

**Screenshots**

**Additional context**

**Discord contact**: khrystyiandanylenko

**Comment by KhrysAK47** [comment]
Here video: 
https://imgur.com/a/TYhqLTK

**Comment by KhrysAK47** [comment]
Update: looks like it's an issue if a player is online for too long, as if a player profile expires while in-game, auctions just bug.

This message received and players with it can't trade:
`Player profile key for (PLAYER) has expired!`

**Comment by erikzimmermann** [comment]
Which plugin printed that message?

**Comment by erikzimmermann** [comment]
Please comment if this is still an active issue
