### ISSUE TITLE
Bedrock crash

### ISSUE THREAD

**Issue by Rexi666** [erikzimmermann/TradeSystem#535]
Bedrock players crash when cancel a trade

**To Reproduce**
1. Java player send trade to a bedrock player
2. Bedrock player accepts
3. When on trade screen, java player cancel trade
4. Bedrock player will crash on a black screen

**Expected behavior**
The trade should be canceled without crashing

**Screenshots**
https://cdn.discordapp.com/attachments/1240441223739871302/1240441224016433194/VID-20240515-WA0011.mp4?ex=6649de2a&is=66488caa&hm=fc814cd278789a1456323f22c85b34d49ba2f03b37b470fab10752ec7f1d79f8&

**Discord contact**: rexigamer

**Comment by onebeastchris** [comment]
Hey, Geyser developer here - i'm not able to reproduce the crash on my end (which would be a Geyser bug, as it doesnt happen on Java). Does it still occur for you?

**Comment by Rexi666** [comment]
I'm testing and it seems to be solved, thanks!
