### ISSUE TITLE
Bedrock Clients Automatically Cancels Trade

### ISSUE THREAD

**Issue by TheCrafter8000** [erikzimmermann/TradeSystem#547]
When a java and bedrock player trade with each other and click confirm, during the countdown at a random time it will cancel.

**To Reproduce**
1. Install Geyser
2. Have a java have bedrock client trade with each other
3. Confirm the trade

**Expected behavior**
Continue the countdown and complete the trade

**Discord contact**: thecrafter8000

**Comment by TheCrafter8000** [comment]
I just discovered a "fix" to it is to disable the countdown entirely

**Comment by TheCrafter8000** [comment]
also im figuring out now that my bedrock clients are being rendered at bedrock players at all. They are being sent java messages. The setup i have is a velocity proxy with geyser on it connected to a purpur server with the trade plugin on it

**Comment by PythonChicken123** [comment]
> also im figuring out now that my bedrock clients are not being rendered at bedrock players at all. They are being sent java messages. The setup i have is a velocity proxy with geyser on it connected to a purpur server with the trade plugin on it

Do you have floodgate installed in the server because its a dependency to tell whether a player is on bedrock or java?

**Comment by djoey123** [comment]
Sadly it is still an bug @erikzimmermann 

tested on:
velocity: 3.3.0
Paper-497 (1.20.4)
Geyser: 2.4.4-b704
Tradesystem: 2.6.2

See video:
https://youtu.be/hrTbahztuZQ

java player to bedrock player
