### ISSUE TITLE
[Countdown extension] Changing layout

### ISSUE THREAD

**Issue by erikzimmermann** [erikzimmermann/TradeSystem#65]
Source: https://www.spigotmc.org/threads/trade-system-custom-layouts.327308/page-3

Iskandarluqman: "Just a quick suggestion, if you disable in config the money, then in the editor you shouldnt be force :D But that is a way for improvement. I actually looking forward if you can make it have animations? For example in my layout. When both agree then the glass panes in the middle (5 black stained) in this picture will change to yellow one by one until its done countdown. This will give like extra time if they want to change their mind. Maybe in the editor add an option in Functions perhaps called Countdown {Optional}. With optional which mean they can still continue to amigious althought its not been set. Then in the Countdown section, add a 1 second, 2 second , 3 second, 4 second and 5 second. When you press the 1 second, it will just show like the GUI editor, you can select which one you wanna make it the first thing to be change when a countdown begin. Im bad at explaining this, bacisly can you add a countdown which will have an awesome animations? xD"

**Comment by LE0ZY** [comment]
Any updates?
Looking forward to this

**Comment by MesterDavid** [comment]
I want this too. 

Please. You can make it.
